export const CATEGORIES = [
  "dagligvarer",
  "snacks og småkjøp",
  "husleie",
  "strøm",
  "takeaway",
  "transport",
  "trening",
  "sosialt",
  "underholdning",
  "abonnement",
  "studier og pensum",
  "helse",
  "personlig pleie",
  "forsikring",
  "klær",
  "elektronikk",
  "hjem og interiør",
  "reise",
  "gaver og donasjoner",
  "lønn",
  "studielån og stipend",
  "annen inntekt",
  "nedbetaling av lån",
  "gebyrer og skatt",
  "sparing",
  "overføring",
  "other",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_LABELS: Record<Category, string> = {
  dagligvarer: "Dagligvarer",
  "snacks og småkjøp": "Snacks og småkjøp",
  husleie: "Husleie og bolig",
  strøm: "Strøm og oppvarming",
  takeaway: "Restaurant, kafé og takeaway",
  transport: "Transport",
  trening: "Trening",
  sosialt: "Sosialt og uteliv",
  underholdning: "Underholdning",
  abonnement: "Abonnement",
  "studier og pensum": "Studier og pensum",
  helse: "Helse og apotek",
  "personlig pleie": "Personlig pleie",
  forsikring: "Forsikring",
  klær: "Klær og sko",
  elektronikk: "Elektronikk",
  "hjem og interiør": "Hjem og interiør",
  reise: "Reise og ferie",
  "gaver og donasjoner": "Gaver og donasjoner",
  lønn: "Lønn",
  "studielån og stipend": "Studielån og stipend",
  "annen inntekt": "Annen inntekt",
  "nedbetaling av lån": "Nedbetaling av lån",
  "gebyrer og skatt": "Gebyrer og skatt",
  sparing: "Sparing og investering",
  overføring: "Overføring mellom egne kontoer",
  other: "Annet",
};
